### ISSUE TITLE
Can not get values from appsettings.json

### ISSUE THREAD

**Issue by NeoKendall** [task-it/TaskIt.NLog.Targets.Teams#2]
Hello!

I declared a variable:
`<variable name="teamsUrl" value="${configsetting:name=Logging.TeamsUrl}"/>`

and then i used it like this:
```
<target xsi:type="MsTeams"
        name="teams"
        Url="${teamsUrl}"
        ApplicationName="ApplicationName"
        Environment="dev"/>
```
But it doesn't work.
Is it possible to use values from appsettings.json?

**Comment by cbolandK20** [comment]
This matter is more NLog related, but that's possible. 
I haven't tried it, but the NLog Documatation says: yes
See this posts for a how to:
https://github.com/NLog/NLog.Extensions.Logging/pull/263
and 
https://stackoverflow.com/questions/56246416/how-can-i-configure-nlog-in-net-core-with-appsettings-json-instead-of-an-nlog-c

**Comment by NeoKendall** [comment]
Yes, it works for other targets, but not for this.
Even if I use json configuration and specify name using ${configsetting:item=Logging.ApplicationName}, I just get the same string in the application name field on card, not the value from the config. But for default target it works.

**Comment by cbolandK20** [comment]
ok, I will reopen the Issue und have a look. Maybe you could create a branch and modify the test App according to your setup so that I can check it more easily?
Please do not enter your Teams Webhook URL in this branch - I will use mine ;-)

**Comment by NeoKendall** [comment]
I created test app, but I don't have permissions  to push. Could you please provide them?

**Comment by cbolandK20** [comment]
I looks that you forked the whole repo. Can you push to your fork?
I thought more about a feature branch or similar. Maybe I can pull your fork.

**Comment by cboland-task** [comment]
I pulled your fork, but nothing new in there. Can't you pull to your fork?
The creation of a feature branch in the original repo should be possible.
Sorry, I'm not used to work with github,

**Comment by NeoKendall** [comment]
I also don't work with github often:)
I pushed to my fork. Look at this please.

**Comment by cbolandK20** [comment]
Thanks, I looking into it

**Comment by cbolandK20** [comment]
Right now this is unfortunately not supported - BUT ...
I'm working on a 2.0 Version (with easier custom message cards) and will add this feature

**Comment by snakefoot** [comment]
Created #4 that adds Layout-support of Application + Environment + Url

**Comment by NeoKendall** [comment]
> Right now this is unfortunately not supported - BUT ...
> I'm working on a 2.0 Version (with easier custom message cards) and will add this feature

Thanks!

**Comment by cbolandK20** [comment]
Version 2.0.0 is out on nuget. Thanks
